### ISSUE TITLE
[Bug] Cyrillic language trouble

### ISSUE THREAD

**Issue by kodersha** [tomaae/WooferBot#10]
**Describe the bug**
Cyrillic characters are not supported.

**To Reproduce**
I write command on Russian language in `settings.json` file, but after saving this file and restart Bot I get strange symbols.

**Expected behavior**
I want normal readable cyrillic characters.

**Screenshots**
![01](https://user-images.githubusercontent.com/16720880/69364997-fe22b700-0cc5-11ea-9355-0150b7d05f0a.png)
After save and Bot restart
![02](https://user-images.githubusercontent.com/16720880/69365009-01b63e00-0cc6-11ea-9a42-d7b215d990da.png)

**Software (please complete the following information):**
 - OS: Windows 10
 - OBS latest version

**Comment by tomaae** [comment]
When you save the file and open it again without starting the bot, are those characters still correct?
If so, can you write those characters here so I can have a look?

**Comment by kodersha** [comment]
> When you save the file and open it again without starting the bot, are those characters still correct?
> If so, can you write those characters here so I can have a look?

Yes, this characters remain correct. I'm trying to write - `Привет`

**Comment by tomaae** [comment]
If you are using latest version, you can try overwriting lib/settings.py from master branch.

**Comment by kodersha** [comment]
> If you are using latest version, you can try overwriting lib/settings.py from master branch.

Thanks, now it works!
