### ISSUE TITLE
[Bug]windows系统怎么在OBS里面使用？

### ISSUE THREAD

**Issue by xiozoiz** [tomaae/WooferBot#76]
**Describe the bug**

**To Reproduce**
3. See error

**Expected behavior**

**Screenshots**

**Software (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Streaming software [e.g. OBS, SLOBS, XSplit]
 - Streaming software Version [e.g. 22.0.2 64-bit]

**Additional context**

**Comment by xiozoiz** [comment]
How can windows system be used in OBS

**Comment by tomaae** [comment]
I'm not sure what you are asking for
